name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - run: npm i -g pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - run: pnpm run compile

      - run: ls

      - run: pnpm run build

      - run: pnpm vsce publish --pat ${{ secrets.MARKETPLACE_TOKEN }} --no-dependencies
